# -*- coding: utf-8 -*-
"""task6_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLtBVHOYR1Tzm4svttQj734HyKBWBTu7
"""

import pandas as pd
def row_col_num(filename):
  df=pd.read_csv(filename)
  rows,cols=df.shape
  return f"В таблице {rows} строк и {cols} столбцов"

